### ISSUE TITLE
Error when rendering particular molecule from metatlas dataset

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/mongochemclient#136]
Formula: C24H51O39S6
INCHIKey: CAKDYPYEIQSZJT-UHFFFAOYSA-N

![screen](https://user-images.githubusercontent.com/1031053/62958585-0618b400-bdc5-11e9-8337-bc0b5ed97eca.png)

**Comment by cryos** [comment]
Is there a place we could get at the CJSON it sees?

**Comment by cjh1** [comment]
[Here](https://gist.github.com/cjh1/6eaf5a0c314d51842285460db82964ff) is an example of a failing CJSON

**Comment by cryos** [comment]
That is weird, it looks totally valid, and renders as expected in Avogadro 2. I guess something is going wrong in the 3dmol code somewhere, but I can't imagine what.

**Comment by psavery** [comment]
I've also encountered some molecules from qcarchive that do not render with 3dMol.js, but they do render with VTK.js.

However, I don't see any errors in the javascript console when these fail to render, so I am not sure if this is related to this issue.

Two examples are attached below. 

[mol1.cjson.gz](https://github.com/OpenChemistry/mongochemclient/files/3507496/mol1.cjson.gz)
[mol2.cjson.gz](https://github.com/OpenChemistry/mongochemclient/files/3507497/mol2.cjson.gz)

**Comment by psavery** [comment]
It looks like this error is also occurring for [this molecule](https://data.openchemistry.org/molecules/inchikey/RYYVLZVUVIJVGH-UHFFFAOYSA-N) on data.openchemistry.org.

**Comment by psavery** [comment]
@alesgenova

**Comment by cryos** [comment]
@alesgenova do you have any ideas on what is going on here? It isn't clear what is undefined in this context, but it would seem that the 3dmol widget is expecting something that is missing. Ideally it would check that the element was defined before trying to reference attributes and fail more gracefully.

**Comment by cjh1** [comment]
This should now be resolve OpenChemistry/oc-web-components/pull/141, it has also been deployed to data.openchemistry.org.
