### ISSUE TITLE
TypeError on login

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/mongochemclient#141]
I get this error when I log in, and it goes away if I refresh the page. 

I know we can probably fix the error by changing [this line](https://github.com/OpenChemistry/mongochemclient/blob/d4e0bcef8e5a4692f27af6f95fdbcb3bc17e69b6/src/components/header/index.js#L49) to `{ user && user.admin`. Is that an acceptable fix, or should `user` always not be `null` here?

![Screenshot from 2019-09-04 11-50-17](https://user-images.githubusercontent.com/9558430/64270900-48d43480-cf0a-11e9-963d-37a3fc4d52f8.png)

**Comment by cjh1** [comment]
This have been fixed in master, looks like the container is out of data, I will trigger a rebuild.

**Comment by psavery** [comment]
I'm on the master branch when I get the error.
