### ISSUE TITLE
Allow modes to be hidden

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/mongochemclient#16]
Figuring out if we can show/hide the D3 chart without breaking its rendering. I couldn't get it to work if I linked the ng-show to the vibrational modes.

**Comment by cjh1** [comment]
@cryos Are you saying you want the whole right card to be hidden if there are not vibrational modes?

**Comment by cryos** [comment]
Sorry, I filter GitHub emails and only just saw this... No, I was trying to simply hide the chart, but keep the card visible as it shows other things. Ideally the layout would be updated, and the chart shown. I can get it to disappear, and reappear/relayout, but it doesn't seem to get the right dimensions.

**Comment by cryos** [comment]
The diff below is from master, and shows the experimental code we just talked about. It looks like we don't trigger a render after the element gets its new size. I tried a few things in the chart directive, but couldn't get it to work as expected. This should probably just move into its own card, and that should be hidden or shown depending on hasSpectra()

```
diff --git a/app/components/home/home.jade b/app/components/home/home.jade
index 9c8354d..2e0992d 100644
--- a/app/components/home/home.jade
+++ b/app/components/home/home.jade
@@ -16,6 +16,7 @@ md-content(ng-controller="mongochemMolecules", flex, layout="column")
           md-button(ng-click="setViewStyle('stick')") Stick
           md-button(ng-click="setViewStyle('ball')") Ball
       md-card-content(flex='50', layout='column')
+        md-content(mongochem-vibrational-modes-chart, ng-show="hasSpectra()", data="vibrationalModes", style="width: 100%; height: 300px; background-color: transparent;", mongochem-animating="{{isAnimating}}")
         table
           tbody
             tr
@@ -31,7 +32,7 @@ md-content(ng-controller="mongochemMolecules", flex, layout="column")
               td Spectra:
               td(ng-if='hasSpectra()') Yes
               td(ng-if='!hasSpectra()') No
-        md-content(mongochem-vibrational-modes-chart, data="vibrationalModes", style="width: 100%; height: 300px; background-color: transparent;", mongochem-animating="{{isAnimating}}")
+
     md-card
       md-card-content(layout="row", layout-align="start center")
         h2.md-title Molecule:
```

**Comment by cryos** [comment]
Looks good, I think we can close this.
