### ISSUE TITLE
Not able to go to Vibration Mode from Energy mode

### ISSUE THREAD

**Issue by rtgdk** [OpenChemistry/mongochemclient#60]
![screenshot from 2017-03-28 22-20-10](https://cloud.githubusercontent.com/assets/17159160/24417273/6ce73542-1405-11e7-90de-c24b2eaa9442.png)
While in Energy Type Mode, there is no way to click Vibrations Type as it lies over the 3D model of molecule.

**Comment by cryos** [comment]
Yes, we need to fix that up. Thanks for the report, hopefully we can come up with something cleaner. You can click on Optimization, and then on Vibrational as a temporary workaround.

**Comment by sarvesh211999** [comment]
We can fix it by adding z-index to the div element

**Comment by cjh1** [comment]
This issue is raise against the previous version, which is no longer supported, should not be an issue with the current version.
